# Generated by Django 4.2.4 on 2023-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='artist',
            field=models.CharField(default='Unknown', help_text='The name of the artist', max_length=50, verbose_name='Artist Name'),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='size',
            field=models.CharField(default='Not specified', help_text='The size of the art piece', max_length=20, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='year',
            field=models.PositiveIntegerField(default=0, help_text='The year when the art piece was created', verbose_name='Year'),
        ),
    ]
