# Generated by Django 4.2.4 on 2023-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_artpiece_artist_artpiece_size_artpiece_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price of the art piece for immediate purchase.', max_digits=10, null=True, verbose_name='Buy Now Price'),
        ),
    ]
