# Generated by Django 4.2.4 on 2023-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_artpiece_buy_now_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='is_on_auction',
            field=models.BooleanField(default=False, help_text='True if the art piece has been on auction.', verbose_name='Is On Auction'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The purchased price of the art piece.', max_digits=10, null=True, verbose_name='Purchased Price'),
        ),
    ]
